baseURL = "https://aldea.dev/"
DefaultContentLanguage="en"
languageCode = "en-us"
title = "Aldea Dev"
theme="beautifulhugo"
googleAnalytics="UA-150668877-1"
pygmentsCodeFences = true
pygmentsUseClasses = true

[Params]
logo="img/logo.png"
copyright = "MIT"

[languages]
  [languages.en]
    weight = 1
    subtitle = "Another small community"

    [[languages.en.menu.main]]
        name = "Blog"
        url = ""
        weight = 2

    [[languages.en.menu.main]]
        name = "About"
        url = "about/"
        weight = 3

  [languages.es]
    weight = 1
    subtitle = "Otra pequeña comunidad"

    [[languages.es.menu.main]]
        name = "Blog"
        url = ""
        weight = 2

    [[languages.es.menu.main]]
        name = "Acerca de"
        url = "about/"
        weight = 3