baseURL = "https://aldea.dev/"
DefaultContentLanguage="es"
languageCode = "es-co"
title = "Aldea Dev"
theme="beautifulhugo"
googleAnalytics="UA-150668877-1"
pygmentsCodeFences = true
pygmentsUseClasses = true
copyright = "MIT"

[Params]
logo="img/logo.png"
subtitle = "Otra pequeña comunidad"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 2
